In [49]:
import pandas as pd
import numpy as np
import os
from sklearn import linear_model


In [50]:
data = pd.read_csv("apartments.csv")
data

Price  Floorspace  Rooms  Lotsize
0  205000          71      4       92
1  209500          98      5      123
2  349500         128      6      114
3  250000          86      4       98
4  419000         173      6       99
5  225000          83      4       67
6  549500         165      6      110
7  240000          71      4       78

In [56]:
reg = linear_model.Ridge()
reg.fit(data[['Floorspace','Rooms','Lotsize']].values,data.Price)

Ridge()

In [57]:
reg.predict([[116,7,115]])


array([308443.94038488])

In [58]:
reg.coef_


array([ 2954.0580517 , -2715.21050124,  -650.03579238])

In [59]:
reg.intercept_


59533.79601900914

In [60]:
reg.predict([[116,6,115]])

array([311159.15088612])